// <auto-generated />
using System;
using Goldnote.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Goldnote.Migrations.MvcGoldnote
{
    [DbContext(typeof(MvcGoldnoteContext))]
    partial class MvcGoldnoteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Goldnote.Models.GoldNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Change")
                        .HasColumnType("boolean");

                    b.Property<string>("CreditCardMachine")
                        .HasColumnType("text");

                    b.Property<bool>("Destination")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("EditDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EditerId")
                        .HasColumnType("text");

                    b.Property<string>("GoldNoteName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoldNoteSendingPaper")
                        .HasColumnType("text");

                    b.Property<string>("ImageAdress")
                        .HasColumnType("text");

                    b.Property<string>("OnAccounting")
                        .HasColumnType("text");

                    b.Property<string>("SpecialOptions")
                        .HasColumnType("text");

                    b.Property<bool>("WithDiscount")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Goldnote");
                });
#pragma warning restore 612, 618
        }
    }
}
